services:
  - type: web
    name: portfolio-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: SECRET_KEY
        value: sua-chave-secreta-aqui